// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'contentContainer': string;
  'contentHeader': string;
  'explorerContainer': string;
  'explorerImage': string;
  'explorerMenu': string;
  'explorerMenuIcon': string;
  'explorerMenuText': string;
  'explorerMenuTitle': string;
  'explorerNavBar': string;
  'grid': string;
  'gridItem': string;
  'gridTitle': string;
  'hidden': string;
  'hiddenItem': string;
  'inlineLink': string;
  'leftMenu': string;
  'navigationBar': string;
  'navigationBarTitle': string;
  'page': string;
  'pageContainer': string;
  'pageHeader': string;
  'polycultureImg': string;
  'polycultureMenu': string;
  'polycultureMenuItem': string;
  'rightMenu': string;
  'scrollContainer': string;
  'select': string;
  'selected': string;
  'selectedNav': string;
  'sliderArrow': string;
  'sliderArrowContainer': string;
  'sliderContainer': string;
  'sliderContent': string;
  'syntropicImg': string;
  'topMarginContainer': string;
  'topMarginContent': string;
  'visibleItem': string;
}
export const cssExports: CssExports;
export default cssExports;
