version: '3'

services:
  db:
    build:
      context: ./database/
      dockerfile: Dockerfile.dev
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: syntropic-db-container

  api:
    build:
      context: ./backend_go/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend_go/uploads/:/go/src/app/uploads
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: syntropic-api-container
    depends_on: 
      - db
    environment:
      - PGHOST=db
