CREATE TABLE hardiness (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value INT NOT NULL
);

CREATE TABLE species (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  min_hardiness INT NOT NULL,
  max_hardiness INT NOT NULL
);

CREATE TABLE materials (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE images (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE species_materials (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_id INT REFERENCES species(uid),
  material_id INT REFERENCES materials(uid),
  image_id INT REFERENCES images(uid),
  link VARCHAR(255)
);

CREATE TABLE agro_eco_systems (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  hardiness INT NOT NULL
);

CREATE TABLE species_agrosystems (
  uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_id INT REFERENCES species(uid),
  agrosystem_id INT REFERENCES agro_eco_systems(uid)
);

INSERT into hardiness(value) VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12), (13), (14), (15);
