CREATE TABLE climates (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  climate VARCHAR(255)
);

CREATE TABLE hardiness (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hardiness INT
);

CREATE TABLE species (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species VARCHAR(255)
);

CREATE TABLE materials (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material VARCHAR(255)
);

CREATE TABLE species_materials (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_id INT REFERENCES species(uid),
  material_id INT REFERENCES materials(uid)
);

CREATE TABLE species_hardiness (
  uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_id INT REFERENCES species(uid),
  hardiness_id INT REFERENCES hardiness(uid)
);
